package com.nt.entity;
// Generated May 18, 2019 5:19:10 PM by Hibernate Tools 5.2.3.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Insurancepolicy generated by hbm2java
 */
@Entity
@Table(name = "INSURANCEPOLICY", schema = "SYSTEM")
public class Insurancepolicy implements java.io.Serializable {

	private int policyid;
	private String policyname;
	private Long tenure;
	private String company;
	private BigDecimal initialamount;

	public Insurancepolicy() {
	}

	public Insurancepolicy(int policyid) {
		this.policyid = policyid;
	}

	public Insurancepolicy(int policyid, String policyname, Long tenure, String company, BigDecimal initialamount) {
		this.policyid = policyid;
		this.policyname = policyname;
		this.tenure = tenure;
		this.company = company;
		this.initialamount = initialamount;
	}

	@Id
     @GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name = "POLICYID", unique = true, nullable = false, precision = 5, scale = 0)
	public int getPolicyid() {
		return this.policyid;
	}

	public void setPolicyid(int policyid) {
		this.policyid = policyid;
	}

	@Column(name = "POLICYNAME", length = 20)
	public String getPolicyname() {
		return this.policyname;
	}

	public void setPolicyname(String policyname) {
		this.policyname = policyname;
	}

	@Column(name = "TENURE", precision = 10, scale = 0)
	public Long getTenure() {
		return this.tenure;
	}

	public void setTenure(Long tenure) {
		this.tenure = tenure;
	}

	@Column(name = "COMPANY", length = 10)
	public String getCompany() {
		return this.company;
	}

	public void setCompany(String company) {
		this.company = company;
	}

	@Column(name = "INITIALAMOUNT", precision = 10)
	public BigDecimal getInitialamount() {
		return this.initialamount;
	}

	public void setInitialamount(BigDecimal initialamount) {
		this.initialamount = initialamount;
	}

}
