package com.nt.entity;
// Generated May 22, 2019 5:46:31 PM by Hibernate Tools 5.2.3.Final



/**
 * Employee generated by hbm2java
 */
public class NGOMember implements java.io.Serializable {

	private int mid;
	private String mname;
	private String desg;
	private float salary;

	public NGOMember() {
	}

	public NGOMember(int mid) {
		this.mid = mid;
	}

	public NGOMember(int mid, String mname, String desg, float salary) {
		this.mid = mid;
		this.mname = mname;
		this.desg = desg;
		this.salary = salary;
	}

	public int getMid() {
		return this.mid;
	}

	public void setMid(int mid) {
		this.mid = mid;
	}

	public String getMname() {
		return this.mname;
	}

	public void setMname(String mname) {
		this.mname = mname;
	}

	public String getDesg() {
		return this.desg;
	}

	public void setDesg(String desg) {
		this.desg = desg;
	}

	public float getSalary() {
		return this.salary;
	}

	public void setSalary(float salary) {
		this.salary = salary;
	}

}
